// Code generated by protoc-gen-go. DO NOT EDIT.
// source: birdComm.proto

/*
Package birdComm is a generated protocol buffer package.

It is generated from these files:
	birdComm.proto

It has these top-level messages:
	Result
	PeerGroup
	Peer
	Route
	RouteGroup
*/
package birdComm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	Reply   string `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PeerGroup struct {
	Peer map[string]*Peer `protobuf:"bytes,1,rep,name=peer" json:"peer,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PeerGroup) Reset()                    { *m = PeerGroup{} }
func (m *PeerGroup) String() string            { return proto.CompactTextString(m) }
func (*PeerGroup) ProtoMessage()               {}
func (*PeerGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PeerGroup) GetPeer() map[string]*Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type Peer struct {
	Address     string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	As          uint32 `protobuf:"varint,3,opt,name=as" json:"as,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetAs() uint32 {
	if m != nil {
		return m.As
	}
	return 0
}

func (m *Peer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Peer) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Route struct {
	Prefix  string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Mask    uint32 `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	Nexthop string `protobuf:"bytes,3,opt,name=nexthop" json:"nexthop,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Route) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Route) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *Route) GetNexthop() string {
	if m != nil {
		return m.Nexthop
	}
	return ""
}

type RouteGroup struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *RouteGroup) Reset()                    { *m = RouteGroup{} }
func (m *RouteGroup) String() string            { return proto.CompactTextString(m) }
func (*RouteGroup) ProtoMessage()               {}
func (*RouteGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RouteGroup) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "birdComm.result")
	proto.RegisterType((*PeerGroup)(nil), "birdComm.peer_group")
	proto.RegisterType((*Peer)(nil), "birdComm.peer")
	proto.RegisterType((*Route)(nil), "birdComm.route")
	proto.RegisterType((*RouteGroup)(nil), "birdComm.route_group")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BirdComm service

type BirdCommClient interface {
	AddNeighbour(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*Result, error)
	DeleteNeighbour(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*Result, error)
	AddStatic(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Result, error)
	DeleteStatic(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Result, error)
}

type birdCommClient struct {
	cc *grpc.ClientConn
}

func NewBirdCommClient(cc *grpc.ClientConn) BirdCommClient {
	return &birdCommClient{cc}
}

func (c *birdCommClient) AddNeighbour(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/birdComm.bird_comm/add_neighbour", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *birdCommClient) DeleteNeighbour(ctx context.Context, in *Peer, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/birdComm.bird_comm/delete_neighbour", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *birdCommClient) AddStatic(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/birdComm.bird_comm/add_static", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *birdCommClient) DeleteStatic(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/birdComm.bird_comm/delete_static", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BirdComm service

type BirdCommServer interface {
	AddNeighbour(context.Context, *Peer) (*Result, error)
	DeleteNeighbour(context.Context, *Peer) (*Result, error)
	AddStatic(context.Context, *Route) (*Result, error)
	DeleteStatic(context.Context, *Route) (*Result, error)
}

func RegisterBirdCommServer(s *grpc.Server, srv BirdCommServer) {
	s.RegisterService(&_BirdComm_serviceDesc, srv)
}

func _BirdComm_AddNeighbour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirdCommServer).AddNeighbour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birdComm.bird_comm/AddNeighbour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirdCommServer).AddNeighbour(ctx, req.(*Peer))
	}
	return interceptor(ctx, in, info, handler)
}

func _BirdComm_DeleteNeighbour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirdCommServer).DeleteNeighbour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birdComm.bird_comm/DeleteNeighbour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirdCommServer).DeleteNeighbour(ctx, req.(*Peer))
	}
	return interceptor(ctx, in, info, handler)
}

func _BirdComm_AddStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Route)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirdCommServer).AddStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birdComm.bird_comm/AddStatic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirdCommServer).AddStatic(ctx, req.(*Route))
	}
	return interceptor(ctx, in, info, handler)
}

func _BirdComm_DeleteStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Route)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirdCommServer).DeleteStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birdComm.bird_comm/DeleteStatic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirdCommServer).DeleteStatic(ctx, req.(*Route))
	}
	return interceptor(ctx, in, info, handler)
}

var _BirdComm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "birdComm.bird_comm",
	HandlerType: (*BirdCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add_neighbour",
			Handler:    _BirdComm_AddNeighbour_Handler,
		},
		{
			MethodName: "delete_neighbour",
			Handler:    _BirdComm_DeleteNeighbour_Handler,
		},
		{
			MethodName: "add_static",
			Handler:    _BirdComm_AddStatic_Handler,
		},
		{
			MethodName: "delete_static",
			Handler:    _BirdComm_DeleteStatic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "birdComm.proto",
}

func init() { proto.RegisterFile("birdComm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x99, 0xb4, 0x89, 0xcd, 0x09, 0xa9, 0x65, 0x10, 0x09, 0x5d, 0x48, 0x08, 0x82, 0x59,
	0x55, 0x8c, 0x22, 0x17, 0xb7, 0x22, 0xae, 0x04, 0x99, 0x17, 0x28, 0xd3, 0xcc, 0xf1, 0xde, 0x70,
	0x93, 0xcc, 0x30, 0x33, 0xd1, 0xdb, 0xad, 0x3b, 0x1f, 0xd1, 0xb7, 0x91, 0x99, 0x24, 0x6d, 0x2d,
	0x2e, 0xbc, 0xbb, 0xf9, 0x9d, 0x3f, 0xdf, 0xf7, 0x71, 0x18, 0x58, 0x1f, 0x1a, 0x2d, 0x3e, 0xca,
	0xae, 0xdb, 0x29, 0x2d, 0xad, 0xa4, 0xab, 0x99, 0x8b, 0x1b, 0x88, 0x34, 0x9a, 0xa1, 0xb5, 0xf4,
	0x19, 0x84, 0x1a, 0x55, 0x7b, 0xcc, 0x48, 0x4e, 0xca, 0x98, 0x8d, 0x40, 0x33, 0x78, 0x62, 0x86,
	0xba, 0x46, 0x63, 0xb2, 0x20, 0x27, 0xe5, 0x8a, 0xcd, 0x58, 0xfc, 0x22, 0x00, 0x0a, 0x51, 0xef,
	0x6f, 0xb5, 0x1c, 0x14, 0xad, 0x60, 0xe9, 0x28, 0x23, 0xf9, 0xa2, 0x4c, 0xaa, 0x17, 0xbb, 0xb3,
	0xe3, 0x69, 0x66, 0xf7, 0x15, 0x51, 0x7f, 0xea, 0xad, 0x3e, 0x32, 0x3f, 0xbb, 0xfd, 0x0c, 0xf1,
	0xa9, 0x44, 0x37, 0xb0, 0xb8, 0xc7, 0xd9, 0xdd, 0x3d, 0xe9, 0x4b, 0x08, 0xbf, 0xf3, 0x76, 0x40,
	0xef, 0x9c, 0x54, 0xeb, 0xbf, 0x35, 0xd9, 0xd8, 0xfc, 0x10, 0xdc, 0x90, 0xe2, 0x27, 0x19, 0xdd,
	0x5d, 0x5c, 0x2e, 0x84, 0x76, 0x71, 0x47, 0xa1, 0x19, 0x29, 0x85, 0x65, 0xcf, 0xbb, 0x51, 0x2b,
	0x66, 0xfe, 0x4d, 0xd7, 0x10, 0x70, 0x93, 0x2d, 0x72, 0x52, 0xa6, 0x2c, 0xe0, 0x86, 0xe6, 0x90,
	0x08, 0x34, 0xb5, 0x6e, 0x94, 0x6d, 0x64, 0x9f, 0x2d, 0xfd, 0xe8, 0x65, 0x89, 0x6e, 0x61, 0xa5,
	0xb8, 0x31, 0x3f, 0xa4, 0x16, 0x59, 0xe8, 0xdb, 0x27, 0x2e, 0xbe, 0x40, 0xa8, 0xe5, 0x60, 0x91,
	0x3e, 0x87, 0x48, 0x69, 0xfc, 0xd6, 0x3c, 0x4c, 0x19, 0x26, 0x72, 0x11, 0x3a, 0x6e, 0xee, 0x7d,
	0x84, 0x94, 0xf9, 0xb7, 0x0b, 0xdc, 0xe3, 0x83, 0xbd, 0x93, 0xca, 0xe7, 0x88, 0xd9, 0x8c, 0xc5,
	0x7b, 0x48, 0xbc, 0xdc, 0x74, 0xdf, 0x57, 0x10, 0x79, 0x34, 0xd3, 0x85, 0x9f, 0x9e, 0xaf, 0xe1,
	0xeb, 0x6c, 0x6a, 0x57, 0xbf, 0x09, 0xc4, 0xae, 0xb5, 0xaf, 0x65, 0xd7, 0xd1, 0x37, 0x90, 0x72,
	0x21, 0xf6, 0x3d, 0x36, 0xb7, 0x77, 0x07, 0x39, 0x68, 0x7a, 0x75, 0xc5, 0xed, 0xe6, 0x42, 0x67,
	0xfc, 0x08, 0xef, 0x60, 0x23, 0xb0, 0x45, 0x8b, 0x8f, 0xda, 0x7a, 0x0d, 0xe0, 0x8c, 0x8c, 0xe5,
	0xb6, 0xa9, 0xe9, 0x75, 0xba, 0x7f, 0x2c, 0x54, 0x90, 0x4e, 0x36, 0xff, 0xbd, 0x73, 0x88, 0xfc,
	0xf7, 0x7d, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x09, 0x1f, 0xf7, 0x90, 0xd0, 0x02, 0x00, 0x00,
}
