// Code generated by protoc-gen-go. DO NOT EDIT.
// source: birdComm.proto

/*
Package birdComm is a generated protocol buffer package.

It is generated from these files:
	birdComm.proto

It has these top-level messages:
	Family
	ConfReply
	Peer
	PeerGroup
*/
package birdComm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Family struct {
	Af uint32 `protobuf:"varint,1,opt,name=af" json:"af,omitempty"`
}

func (m *Family) Reset()                    { *m = Family{} }
func (m *Family) String() string            { return proto.CompactTextString(m) }
func (*Family) ProtoMessage()               {}
func (*Family) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Family) GetAf() uint32 {
	if m != nil {
		return m.Af
	}
	return 0
}

type ConfReply struct {
	Reply   string `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *ConfReply) Reset()                    { *m = ConfReply{} }
func (m *ConfReply) String() string            { return proto.CompactTextString(m) }
func (*ConfReply) ProtoMessage()               {}
func (*ConfReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConfReply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *ConfReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Peer struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Address     string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	As          uint32 `protobuf:"varint,4,opt,name=as" json:"as,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Peer) GetAs() uint32 {
	if m != nil {
		return m.As
	}
	return 0
}

func (m *Peer) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PeerGroup struct {
	Group []*Peer `protobuf:"bytes,1,rep,name=group" json:"group,omitempty"`
}

func (m *PeerGroup) Reset()                    { *m = PeerGroup{} }
func (m *PeerGroup) String() string            { return proto.CompactTextString(m) }
func (*PeerGroup) ProtoMessage()               {}
func (*PeerGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PeerGroup) GetGroup() []*Peer {
	if m != nil {
		return m.Group
	}
	return nil
}

func init() {
	proto.RegisterType((*Family)(nil), "birdComm.family")
	proto.RegisterType((*ConfReply)(nil), "birdComm.conf_reply")
	proto.RegisterType((*Peer)(nil), "birdComm.peer")
	proto.RegisterType((*PeerGroup)(nil), "birdComm.peer_group")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BirdComm service

type BirdCommClient interface {
	CheckConfig(ctx context.Context, in *Family, opts ...grpc.CallOption) (*ConfReply, error)
	ReloadConfig(ctx context.Context, in *Family, opts ...grpc.CallOption) (*ConfReply, error)
}

type birdCommClient struct {
	cc *grpc.ClientConn
}

func NewBirdCommClient(cc *grpc.ClientConn) BirdCommClient {
	return &birdCommClient{cc}
}

func (c *birdCommClient) CheckConfig(ctx context.Context, in *Family, opts ...grpc.CallOption) (*ConfReply, error) {
	out := new(ConfReply)
	err := grpc.Invoke(ctx, "/birdComm.bird_comm/check_config", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *birdCommClient) ReloadConfig(ctx context.Context, in *Family, opts ...grpc.CallOption) (*ConfReply, error) {
	out := new(ConfReply)
	err := grpc.Invoke(ctx, "/birdComm.bird_comm/reload_config", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BirdComm service

type BirdCommServer interface {
	CheckConfig(context.Context, *Family) (*ConfReply, error)
	ReloadConfig(context.Context, *Family) (*ConfReply, error)
}

func RegisterBirdCommServer(s *grpc.Server, srv BirdCommServer) {
	s.RegisterService(&_BirdComm_serviceDesc, srv)
}

func _BirdComm_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Family)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirdCommServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birdComm.bird_comm/CheckConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirdCommServer).CheckConfig(ctx, req.(*Family))
	}
	return interceptor(ctx, in, info, handler)
}

func _BirdComm_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Family)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirdCommServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birdComm.bird_comm/ReloadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirdCommServer).ReloadConfig(ctx, req.(*Family))
	}
	return interceptor(ctx, in, info, handler)
}

var _BirdComm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "birdComm.bird_comm",
	HandlerType: (*BirdCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "check_config",
			Handler:    _BirdComm_CheckConfig_Handler,
		},
		{
			MethodName: "reload_config",
			Handler:    _BirdComm_ReloadConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "birdComm.proto",
}

func init() { proto.RegisterFile("birdComm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xb1, 0x6e, 0xab, 0x40,
	0x10, 0x14, 0x18, 0xfc, 0x60, 0xfd, 0x8c, 0xa2, 0x95, 0x8b, 0x93, 0x2b, 0x84, 0x52, 0x50, 0xb9,
	0x20, 0x52, 0xd2, 0xa4, 0xcb, 0x1f, 0xf0, 0x03, 0xe8, 0x7c, 0x77, 0x38, 0x28, 0x1c, 0x77, 0xda,
	0xb3, 0x15, 0x59, 0x4a, 0x95, 0x2f, 0x8f, 0x38, 0x4c, 0x70, 0x9b, 0x6e, 0x66, 0x76, 0x67, 0x35,
	0x9a, 0x85, 0xec, 0xd8, 0x91, 0x7c, 0x33, 0x5a, 0x1f, 0x2c, 0x99, 0xb3, 0xc1, 0x64, 0xe6, 0x05,
	0x83, 0x75, 0xcb, 0x75, 0xd7, 0x5f, 0x31, 0x83, 0x90, 0xb7, 0x2c, 0xc8, 0x83, 0x72, 0x5b, 0x87,
	0xbc, 0x2d, 0x5e, 0x01, 0x84, 0x19, 0xda, 0x86, 0x94, 0xed, 0xaf, 0xb8, 0x83, 0xd8, 0x03, 0xbf,
	0x90, 0xd6, 0x13, 0x41, 0x06, 0xff, 0xdc, 0x45, 0x08, 0xe5, 0x1c, 0x0b, 0xf3, 0xa0, 0x4c, 0xea,
	0x99, 0x16, 0xdf, 0x01, 0x44, 0x56, 0x29, 0x42, 0x84, 0x68, 0xe0, 0x5a, 0xdd, 0x7c, 0x1e, 0x63,
	0x0e, 0x1b, 0xa9, 0x9c, 0xa0, 0xce, 0x9e, 0x3b, 0x33, 0x78, 0x6b, 0x5a, 0xdf, 0x4b, 0xe3, 0x61,
	0x2e, 0x25, 0x8d, 0x87, 0x57, 0x7e, 0x3a, 0x53, 0x1f, 0xd3, 0xb1, 0xe8, 0x16, 0xd3, 0xe1, 0x1e,
	0x12, 0xcb, 0x9d, 0xfb, 0x34, 0x24, 0x59, 0xec, 0x57, 0x7f, 0x79, 0x51, 0x01, 0x8c, 0x19, 0x9a,
	0x13, 0x99, 0x8b, 0xc5, 0x47, 0x88, 0x3d, 0x60, 0x41, 0xbe, 0x2a, 0x37, 0x55, 0x76, 0x58, 0x4a,
	0x51, 0x8a, 0xea, 0x69, 0x58, 0x7d, 0x41, 0x3a, 0xea, 0x8d, 0x30, 0x5a, 0xe3, 0x33, 0xfc, 0x17,
	0xef, 0x4a, 0x7c, 0x34, 0x63, 0x13, 0xdd, 0x09, 0x1f, 0x16, 0xcf, 0xd4, 0xda, 0x7e, 0xb7, 0x28,
	0x77, 0x6d, 0xbd, 0xc0, 0x96, 0x54, 0x6f, 0xb8, 0xfc, 0xa3, 0xf1, 0xb8, 0xf6, 0xff, 0x79, 0xfa,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x17, 0x0f, 0xaf, 0xb1, 0x01, 0x00, 0x00,
}
